/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Registro;

import GUI.Registro.RegistrarDireccion;
import DBCommands.ConnectDB;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.GroupLayout.Alignment.values;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Allison
 */
public class RegistrarPersona extends javax.swing.JFrame {
public static ArrayList emails = new ArrayList();
public static ArrayList direcciones = new ArrayList();
    /**
     * Creates new form RegistrarPersona
     */
    public RegistrarPersona() {
        initComponents();
        //Color of the Jframe
        this.getContentPane().setBackground(Color.decode("#FBCF86")); //#FBCF86
        //Center the Jframe
        this.setLocationRelativeTo(null);
        //Icon of the JFrame
        ImageIcon img = new ImageIcon("C:\\Users\\Allison\\Documents\\GitHub\\Libreria\\LOGO.png");
        this.setIconImage(img.getImage());
        
        //Set options in ComboBox PersonTypes
        setPersonTypes();
        
        //Disable day comboBox
        cBoxDay.setEnabled(false);
        
        //Set options in year comboBox
        for (int i = 1940; i<=2021; i++){
            cBoxYear.addItem(String.valueOf(i));
        }
        
    }
    
    private void setComboBoxOptions(){
        int month = Integer.parseInt((String) cBoxMonth.getSelectedItem());
        cBoxDay.setModel(new DefaultComboBoxModel());
        cBoxDay.setEnabled(true);
        
        //The amount of days depends on the month selected
        switch (month) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                for(int i = 1; i<=31; i++){
                    cBoxDay.addItem(String.valueOf(i));
                }
                break;
            case 2:
                for(int i = 1; i<=29; i++){
                    cBoxDay.addItem(String.valueOf(i));
                }
                break;
            default:
                for(int i = 1; i<=30; i++){
                    cBoxDay.addItem(String.valueOf(i));
                }
                break;
        }
    }
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblLinea = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegAddress = new javax.swing.JButton();
        btnRegisterEmail = new javax.swing.JButton();
        lblID1 = new javax.swing.JLabel();
        txtFieldID = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        txtFieldFirstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txtFieldLastname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblBirthdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBoxDay = new javax.swing.JComboBox<>();
        cBoxMonth = new javax.swing.JComboBox<>();
        cBoxYear = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblRelationship = new javax.swing.JLabel();
        comboBoxRelationship = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(244, 213, 178));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Bernard MT Condensed", 0, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Register People");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 240, 45));

        btnBack.setBackground(new java.awt.Color(219, 107, 92));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        lblLinea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(255, 255, 255));
        lblLinea.setText("----------------------------------------------");
        getContentPane().add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(233, 148, 105));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btnRegAddress.setBackground(new java.awt.Color(219, 107, 92));
        btnRegAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegAddress.setForeground(new java.awt.Color(153, 51, 0));
        btnRegAddress.setText("Register Address");
        btnRegAddress.setBorder(null);
        btnRegAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegAddressMouseClicked(evt);
            }
        });

        btnRegisterEmail.setBackground(new java.awt.Color(219, 107, 92));
        btnRegisterEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegisterEmail.setForeground(new java.awt.Color(153, 51, 0));
        btnRegisterEmail.setText("Register E-mail");
        btnRegisterEmail.setBorder(null);
        btnRegisterEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterEmailMouseClicked(evt);
            }
        });

        lblID1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(255, 255, 255));
        lblID1.setText("ID Number:");

        lblFirstname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("Fisrtname:");

        lblLastname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("Lastname:");

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblBirthdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthdate.setText("Birthdate");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Month:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Day:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year:");

        cBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", " " }));

        cBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cBoxMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cBoxMonthMouseClicked(evt);
            }
        });
        cBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxMonthActionPerformed(evt);
            }
        });
        cBoxMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cBoxMonthKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBoxDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBoxMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBoxYear, 0, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnRegister.setBackground(new java.awt.Color(172, 188, 138));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(88, 140, 126));
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address:");

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setForeground(new java.awt.Color(255, 204, 153));

        lblRelationship.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRelationship.setForeground(new java.awt.Color(255, 255, 255));
        lblRelationship.setText("Relationship");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxRelationship, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRelationship)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFieldFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFieldID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldLastname))
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblID1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblAddress)
                        .addGap(3, 3, 3)
                        .addComponent(btnRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 500, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personaanimada1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setPersonTypes(){
        
        //ArrayList to save the person types
        ArrayList<String> tipos = new ArrayList<String>();
        
        try {
            //Get the types from the db
            tipos = ConnectDB.get_PersonType();
            
            //Set the types on the comboBox
            for (int i = 0; i<tipos.size(); i++){
                
                comboBoxRelationship.addItem(tipos.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPersona.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al cargar tipos de persona.");
        }
    }
    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        
        String Firstname, Lastname, Birthdate, PersonType;
        int ID_Number, ID_PersonType;
        
        // Get the data 
        Firstname = txtFieldFirstname.getText();
        Lastname = txtFieldLastname.getText();
        Birthdate = cBoxMonth.getSelectedItem()+","+cBoxDay.getSelectedItem()+","+cBoxYear.getSelectedItem();
        ID_Number = Integer.parseInt(txtFieldID.getText());
        PersonType = comboBoxRelationship.getSelectedItem().toString();
        
        
        try {
            //Se hace la consulta por el ID del tipo de persona
            ID_PersonType = ConnectDB.get_PersonTypeID(PersonType);
            //Se ingresa la persona en la BD
            int result = ConnectDB.insertPerson(ID_Number,ID_PersonType, Firstname, Lastname, Birthdate);
            //If the function returns a 0, it means that the ID wasn´t registered
            if (result == 0){
                //If there are emails on the list
                if (emails.size()>0){

                    //se recorren
                    for (int i=0; i<emails.size(); i++){
                        String email = emails.get(i).toString();

                        //Se agregan a la BD
                        ConnectDB.insertEmail(ID_Number, email);
                    }
                     //vaciar las listas
                    emails.clear();
                }

                //Si hay direcciones registradas
                if (direcciones.size()>0){

                    //Se recorren
                    for (int i = 0; i<direcciones.size(); i++){
                        String direccion = direcciones.get(i).toString();

                        //Se agregan a la BD
                        ConnectDB.insertAddress(ID_Number, direccion);
                    }
                    
                }
                JOptionPane.showMessageDialog(null,"Person registered succesfully! :)");
                //Ponemos los campos en blanco
                txtFieldID.setText(null);
                txtFieldFirstname.setText(null);
                txtFieldLastname.setText(null);
                cBoxDay.setEnabled(false); 
                emails.clear();
                direcciones.clear();
            }else{
                JOptionPane.showMessageDialog(null, "ID already registered on the system! Check that the ID is correct, also you can go and check the people that is already registeted.");
                //Ponemos los campos en blanco
                txtFieldFirstname.setText(null);
                txtFieldLastname.setText(null);
                emails.clear();
                direcciones.clear();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarPersona.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al insertar persona");
            
            //Ponemos los campos en blanco
            txtFieldID.setText(null);
            txtFieldFirstname.setText(null);
            txtFieldLastname.setText(null);
            cBoxDay.setEnabled(false); 
            emails.clear();
            direcciones.clear();
        }
        
       
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnRegisterEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterEmailMouseClicked
        // TODO add your handling code here:
        RegistrarCorreo registrar = new RegistrarCorreo();
        registrar.setVisible(true);
    }//GEN-LAST:event_btnRegisterEmailMouseClicked

    private void btnRegAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegAddressMouseClicked
        // TODO add your handling code here:
        RegistrarDireccion registrar = new RegistrarDireccion();
        registrar.setVisible(true);
    }//GEN-LAST:event_btnRegAddressMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cBoxMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cBoxMonthMouseClicked
        // TODO add your handling code here:
        setComboBoxOptions();
    }//GEN-LAST:event_cBoxMonthMouseClicked

    private void cBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxMonthActionPerformed
        // TODO add your handling code here:
        setComboBoxOptions();
    }//GEN-LAST:event_cBoxMonthActionPerformed

    private void cBoxMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cBoxMonthKeyPressed
        // TODO add your handling code here:
        setComboBoxOptions();
    }//GEN-LAST:event_cBoxMonthKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegAddress;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterEmail;
    private javax.swing.JComboBox<String> cBoxDay;
    private javax.swing.JComboBox<String> cBoxMonth;
    private javax.swing.JComboBox<String> cBoxYear;
    private javax.swing.JComboBox<String> comboBoxRelationship;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblRelationship;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFieldFirstname;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtFieldLastname;
    // End of variables declaration//GEN-END:variables
}
